INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('8', '3', '3', 'Ibuprofeno 200mg. 20 comprimidos masticables', '2024-05-05', '10', 'Pfizer', 'Ibupiretas Junior', '20', '500', 'ibupiretas-junior-pfizer.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('10', '3', '3', 'Mometazona furoato 50mg. spray nasal', '2025-10-09', '4', 'Siegfried', 'Hexaler Nasal', '10', '1500', 'hexaler-nasal-siegfried.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('7', '3', '3', 'Alivia dolores y malestares digestivos. 10 cápsulas blandas', '2023-10-01', '12', 'Propinox', 'Sertal Perlas', '15', '800', 'sertal-perlas-propinox.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('6', '2', '3', 'Meprednisona 8mg. 20 comprimidos ranurados', '2024-10-10', '11', 'Biotenk', 'La Meprednisona Biotenk', '25', '1400', 'meprednisona-biotenk.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('12', '7', '3', 'Suplemento dietari. 120 Cápsulas blandas', '2023-08-02', '15', 'Colbras', 'Valcatil MAx', '80', '12000', 'valcatil-max-colbras.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('17', '5', '4', 'Jabón líquido para diluir. Rinde 3 litros', '2024-05-04', '7', 'Unilever', 'Skip para diluir', '450', '1500', 'jabon-skip-unilever.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('20', '9', '4', '4 unidades x 30mts', '2033-04-03', '19', 'Dia', 'Papel higiénico hoja simple', '350', '250', 'papel-higienico-dia.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('23', '4', '4', 'Poderoso Removedor de Sarro', '2023-07-12', '9', 'Harpic', 'Power Plus', '515', '650', 'power-plus-harpic.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('25', '4', '4', 'Bioactive. Crema multiuso', '2024-03-02', '8', 'Unilever', 'Cif crema', '750', '465', 'cif-crema-unilever.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('45', '15', '5', 'Alimento para gatos adultos sabor carne y pollo', '2025-10-05', '40', 'Purina', 'Cat Chow', '3000', '2600', 'cat-chow-purina.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('40', '20', '5', 'Piedras sanitarias', '2035-01-01', '30', 'Dry Way', 'Piedras sanitarias', '3000', '250', 'piedras-sanitarias-dryway.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('80', '25', '5', 'Alimento para perros. Alda digestibilidad', '2024-11-14', '50', 'Maintenance Criadores', 'Carne y pollo. Adultos', '15000', '5000', 'carne-pollo-maintenance-criadores.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('17', '6', '2', 'Tipo 000', '2023-11-15', '10', 'Dia', 'Harina de Trigo', '1000', '150', 'harina-tres-ceros-dia.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('18', '6', '2', 'Parcialmente descremada', '2023-07-02', '9', 'Dia', 'Leche larga vida', '900', '250', 'leche-larga-vida-descremada-dia.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('9', '5', '2', 'Porotos secos remojados', '2024-02-03', '8', 'Monte Nevi', 'Porotos', '203', '200', 'porotos-montenevi.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('3', '17', '2', 'Fideos secos', '2026-03-12', '11', 'Terrabusi', 'Fideos Ave Maria', '500', '200', 'fideos-ave-maria-terrabusi.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('18', '3', '2', 'Cacao granulado', '2024-09-04', '12', 'La virginia', 'Chocolino', '180', '450', 'chocolino-lavirginia.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('18', '6', '1', 'Medallón de carne', '2023-10-10', '14', 'GoodMArk', 'Hamburguesas clásicas', '320', '700', 'hamburguesa-goodmark.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('17', '3', '1', 'Milanesas de soja tipo caseras', '2024-09-01', '17', 'Granja del Sol', 'Milanesa de soja', '660', '1000', 'milanesa-soja-granjadelsol.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('15', '5', '1', 'Papas noissettes', '2024-09-02', '17', 'Mc Cain', 'Papas noisettes', '500', '800', 'papas-noisette-mccain.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('5', '4', '0', 'Manteca calidad extra', '2023-07-06', '10', 'La Serenisima', 'Manteca', '200', '600', 'manteca-laserenisima.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('9', '7', '0', 'Queso untable clasico', '2023-07-14', '6', 'La serenisima', 'Queso untable', '290', '500', 'queso-untable-laserenisima.jpg');
INSERT INTO `aplicacion`.`producto` (`alto`, `ancho`, `categoria`, `descripcion`, `fechaVencimiento`, `largo`, `marca`, `nombre`, `peso`, `precioArs`, `img`) VALUES ('20', '4', '0', 'Leche deslactosada', '2023-07-30', '12', 'La serenisima', 'Leche deslactosada fresca', '900', '350', 'leche-fresca-deslactosada.jpg');

UPDATE `aplicacion`.`producto` SET `peso` = '0.02' WHERE (`id` = '1');
UPDATE `aplicacion`.`producto` SET `peso` = '0.01' WHERE (`id` = '2');
UPDATE `aplicacion`.`producto` SET `peso` = '0.015' WHERE (`id` = '3');
UPDATE `aplicacion`.`producto` SET `peso` = '0.025' WHERE (`id` = '4');
UPDATE `aplicacion`.`producto` SET `peso` = '0.085' WHERE (`id` = '5');
UPDATE `aplicacion`.`producto` SET `peso` = '0.45' WHERE (`id` = '6');
UPDATE `aplicacion`.`producto` SET `peso` = '0.35' WHERE (`id` = '7');
UPDATE `aplicacion`.`producto` SET `peso` = '0.515' WHERE (`id` = '8');
UPDATE `aplicacion`.`producto` SET `peso` = '0.75' WHERE (`id` = '9');
UPDATE `aplicacion`.`producto` SET `peso` = '3' WHERE (`id` = '10');
UPDATE `aplicacion`.`producto` SET `peso` = '3' WHERE (`id` = '11');
UPDATE `aplicacion`.`producto` SET `peso` = '15' WHERE (`id` = '12');
UPDATE `aplicacion`.`producto` SET `peso` = '1' WHERE (`id` = '13');
UPDATE `aplicacion`.`producto` SET `peso` = '0.9' WHERE (`id` = '14');
UPDATE `aplicacion`.`producto` SET `peso` = '0.203' WHERE (`id` = '15');
UPDATE `aplicacion`.`producto` SET `peso` = '0.5' WHERE (`id` = '16');
UPDATE `aplicacion`.`producto` SET `peso` = '0.18' WHERE (`id` = '17');
UPDATE `aplicacion`.`producto` SET `peso` = '0.32' WHERE (`id` = '18');
UPDATE `aplicacion`.`producto` SET `peso` = '0.66' WHERE (`id` = '19');
UPDATE `aplicacion`.`producto` SET `peso` = '0.5' WHERE (`id` = '20');
UPDATE `aplicacion`.`producto` SET `peso` = '0.2' WHERE (`id` = '21');
UPDATE `aplicacion`.`producto` SET `peso` = '0.29' WHERE (`id` = '22');
UPDATE `aplicacion`.`producto` SET `peso` = '0.9' WHERE (`id` = '23');

UPDATE `aplicacion`.`producto` SET `volumen` = '120' WHERE (`id` = '2');
UPDATE `aplicacion`.`producto` SET `volumen` = '252' WHERE (`id` = '3');
UPDATE `aplicacion`.`producto` SET `volumen` = '240' WHERE (`id` = '1');
UPDATE `aplicacion`.`producto` SET `volumen` = '132' WHERE (`id` = '4');
UPDATE `aplicacion`.`producto` SET `volumen` = '1260' WHERE (`id` = '5');
UPDATE `aplicacion`.`producto` SET `volumen` = '648' WHERE (`id` = '17');
UPDATE `aplicacion`.`producto` SET `volumen` = '200' WHERE (`id` = '21');
UPDATE `aplicacion`.`producto` SET `volumen` = '360' WHERE (`id` = '15');
UPDATE `aplicacion`.`producto` SET `volumen` = '378' WHERE (`id` = '22');
UPDATE `aplicacion`.`producto` SET `volumen` = '1512' WHERE (`id` = '18');
UPDATE `aplicacion`.`producto` SET `volumen` = '3420' WHERE (`id` = '7');
UPDATE `aplicacion`.`producto` SET `volumen` = '595' WHERE (`id` = '6');
UPDATE `aplicacion`.`producto` SET `volumen` = '561' WHERE (`id` = '16');
UPDATE `aplicacion`.`producto` SET `volumen` = '1275' WHERE (`id` = '20');
UPDATE `aplicacion`.`producto` SET `volumen` = '828' WHERE (`id` = '8');
UPDATE `aplicacion`.`producto` SET `volumen` = '867' WHERE (`id` = '19');
UPDATE `aplicacion`.`producto` SET `volumen` = '800' WHERE (`id` = '9');
UPDATE `aplicacion`.`producto` SET `volumen` = '972' WHERE (`id` = '14');
UPDATE `aplicacion`.`producto` SET `volumen` = '960' WHERE (`id` = '23');
UPDATE `aplicacion`.`producto` SET `volumen` = '1020' WHERE (`id` = '13');
UPDATE `aplicacion`.`producto` SET `volumen` = '27000' WHERE (`id` = '10');
UPDATE `aplicacion`.`producto` SET `volumen` = '24000' WHERE (`id` = '11');
UPDATE `aplicacion`.`producto` SET `volumen` = '10000' WHERE (`id` = '12');

INSERT INTO `aplicacion`.`usuario` (`email`, `password`) VALUES ('123@123', '12!$345HGrtyh67dwd8');

INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('40.0', '40.0', '20.0', '60.0', 'a123bcd', '35.0', '35.0', '0', '96000.0', '96000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('40.0', '40.0', '20.0', '60.0', 'e456fgh', '35.0', '35.0', '0', '96000.0', '96000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('40.0', '40.0', '20.0', '60.0', 'i789jkl', '35.0', '35.0', '0', '96000.0', '96000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('40.0', '40.0', '20.0', '60.0', 'm123nop', '35.0', '35.0', '0', '96000.0', '96000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('40.0', '40.0', '20.0', '60.0', 'q456rst', '35.0', '35.0', '0', '96000.0', '96000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('40.0', '90.0', '80.0', '100.0', 'ab123cd', '75.0', '75.0', '1', '360000.0', '360000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('40.0', '90.0', '80.0', '100.0', 'ef456gh', '75.0', '75.0', '1', '360000.0', '360000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('40.0', '90.0', '80.0', '100.0', 'ij789kl', '75.0', '75.0', '1', '360000.0', '360000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('150.0', '170.0', '150.0', '200.0', 'mn123op', '700.0', '700.0', '2', '5100000.0', '5100000.0');
INSERT INTO `aplicacion`.`vehiculo` (`alto`, `ancho`, `distanciaMaxima`, `largo`, `patente`, `pesoDisponible`, `pesoMaximoSoportado`, `tipoVehiculo`, `volumenDisponible`, `volumenMaximo`) VALUES ('150.0', '170.0', '150.0', '200.0', 'qr456st', '700.0', '700.0', '2', '5100000.0', '5100000.0');

INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('1', '8', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('2', '9', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('3', '3', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('4', '4', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('5', '2', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('6', '23', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('7', '22', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('8', '21', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('9', '12', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('10', '20', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('11', '19', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('12', '18', '1');
INSERT INTO `aplicacion`.`carrito` (`id`, `producto_id`, `usuario_id`) VALUES ('13', '16', '1');
